// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MlHeatmap: typeof import('./src/components/MlHeatmap.vue')['default']
  }
}

export { }
